default_language_version:
    python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
    - id: add-trailing-comma

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.7
  hooks:
    - id: ruff

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black
