

x-app: &app
  env_file:
    - .env
  restart: always

volumes:
  dbdata:
  redis_data:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data:
  es_logs:

services:
  auth:
    container_name: auth
    build: ./auth
    <<: *app
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "auth-service"
    volumes:
      - .:/auth
    expose:
      - ${AUTH_API_UVICORN_PORT}
    ports:
      - ${AUTH_API_UVICORN_PORT}:${AUTH_API_UVICORN_PORT}
    depends_on:
      - db
      - redis
      - logstash
      - elasticsearch

  api-migrations:
    build: ./auth
    <<: *app
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "api-migrations-service"
    volumes:
      - .:/auth
    depends_on:
      - db
      - redis
      - logstash
      - elasticsearch
    command: alembic upgrade head

  db:
    image: ghcr.io/dbsystel/postgresql-partman:14
    container_name: db
    shm_size: 1g
    <<: *app
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "db"
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./etl/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    depends_on:
      - logstash
      - elasticsearch

  redis:
    image: redis:alpine
    container_name: redis
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "redis"
    expose:
      - 6379
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/var/lib/redis
    depends_on:
      - logstash
      - elasticsearch

  nginx:
    image: nginx:1.24
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "nginx"
    volumes:
      - ./tmp/logs/nginx/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/:/etc/nginx/conf.d/:ro
    depends_on:
      - auth
      - rate_limit
      - logstash
      - elasticsearch
    ports:
      - "80:80"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    <<: *app
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "jaeger"
    ports:
      - ${JAEGER_UDP}:6831/udp
      - ${JAEGER_PORT}:16686
    command: [ "--log-level=debug" ]
    depends_on:
      - logstash
      - elasticsearch

  rate_limit:
    build: ./rate_limit
    <<: *app
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "rate-limit-service"
    volumes:
      - .:/rate_limit
    depends_on:
      - auth
      - logstash
      - elasticsearch

  kafka-0:
    image: bitnami/kafka:3.4
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "kafka-0"
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_0_data:/bitnami/kafka
    depends_on:
      - logstash
      - elasticsearch

  kafka-1:
    image: bitnami/kafka:3.4
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "kafka-1"
    ports:
      - "9095:9095"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_1_data:/bitnami/kafka
    depends_on:
      - logstash
      - elasticsearch

  kafka-2:
    image: bitnami/kafka:3.4
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "kafka-2"
    ports:
      - "9096:9096"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_2_data:/bitnami/kafka
    depends_on:
      - logstash
      - elasticsearch

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:${LOGSTASH_PORT}"
        tag: "ui"
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    depends_on:
      - logstash
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044/udp"
      - "9600:9600"  # Порт для проверки состояния
    volumes:
      - ./tmp/logs/nginx/:/var/log/nginx/:ro
      # - ./ELK/deploy/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9600/_node/stats" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9400:9200"
    volumes:
      - ./ELK/deploy/es_logs:/usr/share/elasticsearch/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -s -o /dev/null -w '%{http_code}' http://localhost:9200/_cluster/health | grep -q '200' || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
