# Generated by Django 5.0.7 on 2024-07-13 17:03

import movies.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_filmwork_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.AddField(
            model_name='filmwork',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='file',
            field=models.FileField(null=True, storage=movies.storage.CustomStorage(), upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path_in_storage', models.CharField(max_length=255)),
                ('filename', models.TextField(verbose_name='file name')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('file_type', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'content"."files',
                'indexes': [models.Index(fields=['path_in_storage'], name='idx_file_path'), models.Index(fields=['short_name'], name='idx_file_short_name')],
            },
        ),
    ]
