"""Initial

Revision ID: c4dafce045b3
Revises: 
Create Date: 2024-12-21 20:45:20.668263

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4dafce045b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS movie")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'film_work',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('imdb_rating', sa.Float(), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('genre', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('actors_names', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('writers_names', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('director', sa.String(length=255), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        schema='movie'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_work', schema='movie')
    # ### end Alembic commands ###
