"""New Migration

Revision ID: 6193d19cbb81
Revises: 4df764df8196
Create Date: 2024-12-21 16:15:56.623340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6193d19cbb81'
down_revision: Union[str, None] = '4df764df8196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='profiles_service')
    op.create_unique_constraint(None, 'profiles', ['id'], schema='profiles_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', schema='profiles_service', type_='unique')
    op.drop_column('profiles', 'updated_at', schema='profiles_service')
    # ### end Alembic commands ###
